title: A New Dawn
author: Amaka Okaro
email: missamaks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's pretty easy to talk about what you love for extended periods. In my case, I love to travel!
   Add to this a desire to know it all and a sprinkling of Igbo girl and you get the basic recipe for me
    Amaka Okaro. Traveller, Junior developer (love it), and all round awesome human
    

# social links
twitter_username: @missamaks
github_username:  @AmakaOkaro

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
